### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by mackuy** [estbeetoo/node-red-contrib-lirc#1]
Hi Alexandre, I'm trying to use your node-red-contrib-lirc implementation, but I cannot install it, using npm install node-red-contrib-lirc I get "Registry returned 404 for GET on https://registry.npmjs.org/node-red-contrib-lirc" as the file is not present on the main repository.
May you please send me some indication of how to proceed?
Thanks in advance

**Comment by aborovsky** [comment]
I've published package: https://www.npmjs.com/package/node-red-contrib-lirc
Try to install it now: ```npm install node-red-conrrib-lirc```

**Comment by mackuy** [comment]
Package install right now and I find the node to transmit, not the node to receive, is enough for my needs, I want only let you know that there is only one node present after installation.
Best regards, and thanks for tempestive resolution.
