### ISSUE TITLE
irw?

### ISSUE THREAD

**Issue by krambriw** [estbeetoo/node-red-contrib-lirc#2]
Hello, first of all, thanks for this nice node-red contribution!
So far managed to setup everything fine, sending ir codes from node-red

Using a USB-UIRT, running Node-RED in a RPi

Have you plans or looked into the possibility for a node to allow Node-RED receiving ir codes from the remotes

Best regards, Walter

**Comment by bidyutper** [comment]
help me...How to setup with node red ..how its works..i have no idea

**Comment by ykornilov** [comment]
Good afternoon! Thank you for your attention! We use the equipment "Global Cache" in our projects and in the near future we will not return to the software "lirc"
