### ISSUE TITLE
How to configure "lirc-controller"?

### ISSUE THREAD

**Issue by jonathanschneider** [estbeetoo/node-red-contrib-lirc#3]
What information do I have to enter in "lirc-controller" when adding a "lirc-out" node to get it to communicate with LIRC? Could you please add that to the description? Thanks!

**Comment by ykornilov** [comment]
Hi! "lirc-out" simply binds to "lirc-controller" node. "lirc-out" node contains information about device name for lirc-software, and msg.payload contains name of command. All basic settings are made by configuring lirc-software

**Comment by jonathanschneider** [comment]
Hmm, I have configured LIRC and can trigger IR commands from the command line but in Node-RED the "lirc-out" node still says "Not ready". So I figured I entered the wrong information in the "lirc-controller" field. Anything else I am missing?

**Comment by ykornilov** [comment]
Have you tried sending a trigger IR commands from Node-RED? Can be different output in "lirc-out" node and active output in "lirc-controller" (by default = 1). When sending IR-command, it must switch

**Comment by jonathanschneider** [comment]
Sorry, I hadn’t tried actually triggering it yet since the configuration seemed to have some problem still. It is working now. So just to clarify, the name entered unter „lirc-controller“ is irrelevant, right?

**Comment by aborovsky** [comment]
@jonathanschneider yes, you may define any name for „lirc-controller“ for your convenience
